spring:
  application:
    name: alum-net
    cors:
      allowed-origins: ${APP_CORS_ALLOWED_ORIGINS}
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE_MULTIPART}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs
          valid-issuers: ${VALID-ISSUERS}

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_FUNCTION}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  auth:
    principleAttribute: preferred_username

keycloak:
  name: alum-net
  client-id: ${KEYCLOAK_CLIENT_ID}
  url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}
  username: ${KEYCLOAK_USERNAME}
  password: ${KEYCLOAK_PASSWORD}

logging:
  config: classpath:logback-spring.xml
server:
  port: ${SERVER_PORT}

aws:
  s3:
    bucket-name: ${AWS_BUCKET_NAME}
    region: ${AWS_DEFAULT_REGION}
    base-url: https://${aws.s3.bucket-name}.s3.${aws.s3.region}.amazonaws.com
    duration-url-hours: ${AWS_S3_DURATION_URL_HOURS}

onesignal:
  config:
    id: ${ONESIGNAL_APP_ID}
    rest:
      api-key: ${ONESIGNAL_API_KEY}

mailgun:
  api-key: ${MAILGUN_API_KEY}